/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hck.struts.form;


/** 
 * MyEclipse Struts
 * Creation date: 09-15-2017
 * 
 * XDoclet definition:
 * @struts.form name="administratorForm"
 */
public class AdministratorForm {
	private String admin_name;
	private String admin_pwd;
	private int admin_id;
	private String admin_confirm_pwd;
	public String getAdmin_confirm_pwd() {
		return admin_confirm_pwd;
	}
	public void setAdmin_confirm_pwd(String admin_confirm_pwd) {
		this.admin_confirm_pwd = admin_confirm_pwd;
	}
	public String getAdmin_name() {
		return admin_name;
	}
	public void setAdmin_name(String admin_name) {
		this.admin_name = admin_name;
	}
	public String getAdmin_pwd() {
		return admin_pwd;
	}
	public void setAdmin_pwd(String admin_pwd) {
		this.admin_pwd = admin_pwd;
	}
	public int getAdmin_id() {
		return admin_id;
	}
	public void setAdmin_id(int admin_id) {
		this.admin_id = admin_id;
	}
	@Override
	public String toString() {
		return "AdministratorForm [admin_name=" + admin_name + ", admin_pwd="
				+ admin_pwd + ", admin_id=" + admin_id + "]";
	}
	
	
}