/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hck.struts.form;
/** 
 * MyEclipse Struts
 * Creation date: 09-16-2017
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm{
	private String name;
	private String pwd;
	private boolean root;
	public boolean isRoot() {
		return root;
	}
	public void setRoot(boolean root) {
		this.root = root;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPwd() {
		return pwd;
	}
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	@Override
	public String toString() {
		return "LoginForm [name=" + name + ", pwd=" + pwd + ", root=" + root + "]";
	}
	
}