/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hck.struts.form;

import java.sql.Date;


/** 
 * MyEclipse Struts
 * Creation date: 09-15-2017
 * 
 * XDoclet definition:
 * @struts.form name="newsForm"
 */
public class NewsForm {
	private int news_id ;
	private String news_title;
	private String news_content;
	private Date news_date;
	public int getNews_id() {
		return news_id;
	}
	public void setNews_id(int news_id) {
		this.news_id = news_id;
	}
	public String getNews_title() {
		return news_title;
	}
	public void setNews_title(String news_title) {
		this.news_title = news_title;
	}
	public String getNews_content() {
		return news_content;
	}
	public void setNews_content(String news_content) {
		this.news_content = news_content;
	}
	public Date getNews_date() {
		return news_date;
	}
	public void setNews_date(Date news_date) {
		this.news_date = news_date;
	}
	@Override
	public String toString() {
		return "NewsForm [news_id=" + news_id + ", news_title=" + news_title + ", news_content=" + news_content
				+ ", news_date=" + news_date + "]";
	}
	
}