/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hck.struts.form;

/** 
 * MyEclipse Struts
 * Creation date: 09-15-2017
 * XDoclet definition:
 * @struts.form name="volunteerForm"
 */
public class VolunteerForm {
	private int volunteer_id;
	private String volunteer_name;
	private String volunteer_pwd;
	private int volunteer_age;
	private String volunteer_record;
	private String volunteer_gender;
	private String volunteer_confirm_pwd;
	public String getVolunteer_confirm_pwd() {
		return volunteer_confirm_pwd;
	}
	public void setVolunteer_confirm_pwd(String volunteer_confirm_pwd) {
		this.volunteer_confirm_pwd = volunteer_confirm_pwd;
	}
	public int getVolunteer_id() {
		return volunteer_id;
	}
	public void setVolunteer_id(int volunteer_id) {
		this.volunteer_id = volunteer_id;
	}
	public String getVolunteer_name() {
		return volunteer_name;
	}
	public void setVolunteer_name(String volunteer_name) {
		this.volunteer_name = volunteer_name;
	}
	public String getVolunteer_pwd() {
		return volunteer_pwd;
	}
	public void setVolunteer_pwd(String volunteer_pwd) {
		this.volunteer_pwd = volunteer_pwd;
	}
	public int getVolunteer_age() {
		return volunteer_age;
	}
	public void setVolunteer_age(int volunteer_age) {
		this.volunteer_age = volunteer_age;
	}
	public String getVolunteer_record() {
		return volunteer_record;
	}
	public void setVolunteer_record(String volunteer_record) {
		this.volunteer_record = volunteer_record;
	}
	public String getVolunteer_gender() {
		return volunteer_gender;
	}
	public void setVolunteer_gender(String volunteer_gender) {
		this.volunteer_gender = volunteer_gender;
	}
	@Override
	public String toString() {
		return "VolunteerForm [volunteer_id=" + volunteer_id
				+ ", volunteer_name=" + volunteer_name + ", volunteer_pwd="
				+ volunteer_pwd + ", volunteer_age=" + volunteer_age
				+ ", volunteer_record=" + volunteer_record
				+ ", volunteer_gender=" + volunteer_gender + "]";
	}
	
}